module.exports = [
  {
    name: "club A",
    date: "2024 - October 5 & 6",
    time: "8:30 am to 9 pm",
    address: "123 main ave.",
    description: "music festival",
    site: "www.clubA.com",
  },
  {
    name: "club B",
    date: "2024 - October 12 & 13",
    time: "8:30 am to 9 pm",
    address: "123 main ave.",
    description: "music festival",
    site: "www.clubB.com",
  },
  {
    name: "club C",
    date: "2024 - October 19 & 20",
    time: "8:30 am to 9 pm",
    address: "123 main ave.",
    description: "music festival",
    site: "www.clubC.com",
  },
  {
    name: "club D",
    date: "2024 - October 26 & 27",
    time: "8:30 am to 9 pm",
    address: "123 main ave.",
    description: "music festival",
    site: "www.clubD.com",
  },
  {
    name: "club E",
    date: "2024 - November 2 & 3",
    time: "8:30 am to 9 pm",
    address: "123 main ave.",
    description: "music festival",
    site: "www.clubE.com",
  },
  {
    name: "club F",
    date: "2024 - November 9 & 10",
    time: "8:30 am to 9 pm",
    address: "123 main ave.",
    description: "music festival",
    site: "www.clubF.com",
  },
];
